CXX = g++
CXXFLAGS = -std=c++11 -Wall -g -I.

test_stupid_ptr:
	$(CXX) -o test_bin/stupid_ptr_tests $(CXXFLAGS) test/stupid_ptr_tests.cpp

test_CSV:
	$(CXX) -o test_bin/CSV_tests $(CXXFLAGS) test/CSV_tests.cpp

test_Ticket:		
	$(CXX) -o test_bin/Ticket_tests $(CXXFLAGS) test/Ticket_tests.cpp
